version: "3.9"

services:
  distributed-app:
    container_name: distributed-app
    build:
      context: ./DistributedApp
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - distributed-db
    environment:
      - ConnectionStrings:DefaultConnection= 

  distributed-db:
    container_name: distributed-db
    image: "postgres:15.2-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5445:5432"
    volumes:
      - distributed-db-postgres-volume:/var/lib/postgresql/data

volumes:
  distributed-db-postgres-volume:
